### PR TITLE
Make policyfile path configurable

### LINKED ISSUE #956: Make PolicyFile Path (and name of file) Configurable
I have a bunch of cookbooks wrapped up in a habitat package that share a policyfile. I'd like to implement some chefspec tests inside these cookbooks so that they can be run inside a build phase callback when building the hab package.

Currently I don't see a way to configure this path. Looks to be [hard-coded](https://github.com/chefspec/chefspec/blob/ac4bc68b5cd97241af53bd24da90d06708e570fb/lib/chefspec/policyfile.rb#L25) to `policyfile_path = File.join(Dir.pwd, 'Policyfile.rb')`.

### PR DESCRIPTION
**Pull request by gscho**
Fixes #956 
Signed-off-by: gscho <greg.c.schofield@gmail.com>

### CODE REVIEW

**Comment by gscho** [comment]
Maybe we can add this to #943 and close this?

**Comment by ehvidal** [comment]
Looking forward for this feature! Thank you very much for working on this!

**Comment by tas50** [comment]
Thanks @gscho

**Comment by gscho** [comment]
@tas50 thanks for merging this!

**Pull request merged**
