### PR TITLE
added actions (un)lock to apt,yum,zypper package resource

### PR DESCRIPTION
**Pull request by yeoldegrove**

### CODE REVIEW

**Comment by yeoldegrove** [comment]
The :(un)lock resource was introduced in chef 12.16, therefore the tests for <12.16 fail.
Is there a way to get around these tests or how do we get this merged?

**Comment by tas50** [comment]
You have some travis failures since these actions weren't known in older chef releases

**Comment by yeoldegrove** [comment]
How can I get around these failures? I did not find a workaround or switch for versions...

**Comment by coderanger** [comment]
Why exactly do we need examples for every one of these?

**Comment by yeoldegrove** [comment]
:lock and :unlock are implemented only for apt, yum and zypper, not for any other package type.
That's why I thought this makes sense.

**Comment by coderanger** [comment]
@yeoldegrove What you looked at are just misc example files used as part of the unit testing framework. All actions of all resources are supported automatically, we don't actually have to do anything to support new resources and/or actions.

**Comment by coderanger** [comment]
Did you have specific problems using these actions/resources with ChefSpec?

**Comment by yeoldegrove** [comment]
When I started using chefspec I found the examples in the recipes/spec style very helpful (especially when you're new to the syntax).
I just noticed that these examples are missing and found my commit a useful addition.
If it's enough from your point of view to have this only for the package resource and not e.g. for apt_package resouce, than that's fine with me.

**Comment by tas50** [comment]
There's no real need for this from a testing perspective, but from a docs perspective someone may find it helpful. I have another PR to cleanup the travis config which will fix the reds here.

**Pull request merged**
