### PR TITLE
Deprecate ChefSpec's coverage reporting.

### PR DESCRIPTION
**Pull request by coderanger**
So people are aware they shouldn't use it.

### CODE REVIEW

**Comment by tas50** [comment]
YES!

**Comment by jason-riddle** [comment]
Ok, but what should be used instead?

**Comment by coderanger** [comment]
@jason-riddle Nothing, there is no replacement.

**Comment by iancward** [comment]
If the intent is to deprecate code coverage, you might want to update the description of the repo:
image

**Comment by daxgames** [comment]
But what about people that write GOOD specs that evaluate logic like guards and differing attribute values that cause resource collections to have different contents?  In this case I think the coverage reports are very valuable and the fact there is no replacement is not good for those that do use it and do it right.

**Comment by blackknight36** [comment]
IMO this is an essential feature and should not be removed until there is an alternative available.  Yes, writing unit tests is annoying but it is also essential in ensuring that your recipes work as expected.

**Pull request merged**
