### PR TITLE
Speed up spec execution time

### PR DESCRIPTION
**Pull request by tas50**
Switch examples back to SoloRunner and remove testing on Chef 13.0 - 13.5.

### CODE REVIEW

**Comment by coderanger** [comment]
I want to keep Travis testing on older Chef 13. ChefSpec now has some hilariously intricate code in it and I would like to at least know where it works.

**Comment by tas50** [comment]
Do we really have the expectation that someone can gem install chefspec + old chef?

**Comment by coderanger** [comment]
Yes, it's one of the few cases where that needs to be supported since Bundler is often the only way to test a cookbook with a wide spread of Chef versions if you also want to use latest ChefSpec.

**Comment by tas50** [comment]
I backed out the Travis changes and squashed it all down

**Pull request merged**
