### PR TITLE
WIP: Add example for whyrun_safe_ruby_block

### PR DESCRIPTION
**Pull request by TheLunaticScripter**
This is an integration test that will run the whyrun_safe_ruby_block during chefspec.

Signed-off-by: John Snow <thelunaticscripter@outlook.com>

### CODE REVIEW

**Comment by coderanger** [comment]
Is there a particular reason for this? I wouldn't expect this to be any different from any other resource.

**Comment by TheLunaticScripter** [comment]
This example is to test a specific issue with run_action. In 7.0.0 if the old_run_action method was used against a resource on the runner it would execute the resource. This is just the testing for acceptance to add the the ability for a whyrun_safe_ruby_block to be executed during a chefspec test.

**Comment by coderanger** [comment]
Yes, but why would you ever do that? I think you might be looking for the `step_into` configuration option which allows selecting specific resource types to be actually run during ChefSpec.

**Comment by TheLunaticScripter** [comment]
@coderanger Awesome I will try that thanks for the info.

**Comment by coderanger** [comment]
My "why" question is why are you sending this as a PR? We don't need examples in the tree for every single combination of every feature in ChefSpec.

**Comment by TheLunaticScripter** [comment]
The reason was because there was the potential code change to add back in the old_run_action method to get this functionality back this was the precursor testing to an actual change.

**Comment by coderanger** [comment]
The patching of `run_action` is not a public API, so even if there was a change to it, we won't be fixing it. Going to close this out as `step_into` is the correct way to un-patch resources.

**Pull request closed without merging**
